### ISSUE TITLE
todo 리스트 높이는 동적으로 바뀌어야겠네요

### ISSUE THREAD

**Issue by atobaum** [woowa-techcamp-2020/todo-10#50]
수정하고 다시 푸시했습니다. 지금은 todo 리스트 높이를 강제로 낮췄는데 나중에 입력버튼 로직 추가할때 높이는 동적으로 바뀌어야겠네요

_Originally posted by @LimHaksu in https://github.com/woowa-techcamp-2020/todo-10/pull/48#issuecomment-659233913_

**Comment by LimHaksu** [comment]
이슈 #58 과 같은 내용이므로 이슈 닫습니다.
